"""Common constants used across the application."""

from typing import Dict

from models import CheckSeverity

# File permissions
FILE_PERMISSION_OWNER_RW = 0o600

# Cost thresholds for severity determination
CRITICAL_MONTHLY_SAVINGS_THRESHOLD = 500
HIGH_MONTHLY_SAVINGS_THRESHOLD = 100
MEDIUM_MONTHLY_SAVINGS_THRESHOLD = 50

# Check confidence scores
DEFAULT_CHECK_CONFIDENCE = 0.9
HIGH_CONFIDENCE_THRESHOLD = 0.8
MEDIUM_CONFIDENCE_THRESHOLD = 0.6

# Resource utilization thresholds
CPU_IDLE_THRESHOLD_PERCENT = 5.0
MEMORY_IDLE_THRESHOLD_PERCENT = 10.0
NETWORK_IDLE_THRESHOLD_BYTES = 1_000_000  # 1MB

CPU_RIGHTSIZE_THRESHOLD_PERCENT = 30.0
MEMORY_RIGHTSIZE_THRESHOLD_PERCENT = 30.0

# Time periods
DEFAULT_METRICS_DAYS = 7
DEFAULT_ANALYSIS_DAYS = 14

# Severity display styles
SEVERITY_STYLES: Dict[CheckSeverity, str] = {
    CheckSeverity.CRITICAL: "red bold",
    CheckSeverity.HIGH: "red",
    CheckSeverity.MEDIUM: "yellow",
    CheckSeverity.LOW: "blue",
    CheckSeverity.INFO: "dim",
}

# Severity ordering for filtering
SEVERITY_ORDER = ["info", "low", "medium", "high", "critical"]

# Cloud provider defaults
DEFAULT_AWS_REGION = "us-east-1"
DEFAULT_AZURE_REGION = "eastus"
DEFAULT_GCP_REGION = "us-central1"

# Authentication
AUTH_CALLBACK_PORT = 8080
AUTH_TIMEOUT_SECONDS = 300

# Check-specific constants
MIN_DAYS_VOLUME_UNATTACHED = 7
MAX_SNAPSHOT_AGE_DAYS = 30
MIN_RESERVED_INSTANCE_UTILIZATION_PERCENT = 80.0
TARGET_SAVINGS_PLAN_COVERAGE_PERCENT = 70.0
SAVINGS_PLAN_EXPIRY_WARNING_DAYS = 60
RESERVED_INSTANCE_SAVINGS_ESTIMATE_PERCENT = 25.0
DATABASE_TARGET_CPU_UTILIZATION = 50.0
DATABASE_TARGET_MEMORY_UTILIZATION = 60.0
MIN_SAVINGS_PERCENTAGE_THRESHOLD = 10.0
HIGH_PEAK_CPU_THRESHOLD = 90.0
MEDIUM_PEAK_CPU_THRESHOLD = 80.0
HIGH_PEAK_MEMORY_THRESHOLD = 90.0
MEDIUM_PEAK_MEMORY_THRESHOLD = 80.0