from setuptools import setup, find_packages

setup(
    name="cloud-analyzer-common",
    version="0.1.0",
    description="Multi-cloud cost optimization analyzer - Common Library",
    author="Cloud Analyzer Team",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.11",
    install_requires=[
        "pydantic>=2.5.0",
        "boto3>=1.34.0",
        "azure-mgmt-compute>=30.0.0",
        "azure-mgmt-storage>=21.0.0",
        "azure-mgmt-resource>=23.0.0",
        "azure-identity>=1.15.0",
        "google-cloud-compute>=1.14.0",
        "google-cloud-storage>=2.13.0",
        "google-cloud-resource-manager>=1.11.0",
        "google-auth>=2.25.0",
        "google-auth-oauthlib>=1.2.0",
        "google-auth-httplib2>=0.2.0",
        "google-api-python-client>=2.111.0",
        "msal>=1.26.0",
        "aiohttp>=3.9.1",
        "authlib>=1.3.0",
        "cryptography>=41.0.7",
        "python-dateutil>=2.8.2",
        "typing-extensions>=4.9.0",
    ],
)